// Date: 2011/10/16 08:01:54
// Java generated by Techne
// This is the first stage to more output options
// and therefore a very basic Render-File
// I hope it will be useful, in any case, leave
// feedback so I can improve on it
// - ZeuX
      package net.minecraft.src;

import org.lwjgl.opengl.GL11;

public class RenderDinoEgg extends Render
{

    public RenderDinoEgg(float f)
    {
    	shadowSize = f;
        MainModel = new ModelDinoEgg();
    }

    public void renderDinoEgg(EntityDinoEgg entity, double d, double d1, double d2, 
            float f, float f1)
    {
        {
            GL11.glPushMatrix();
            GL11.glTranslatef((float)d, (float)d1, (float)d2);
            GL11.glRotatef(180F - f, 0.0F, 1.0F, 0.0F);
            float f2 = (float)entity.timeSinceHit - f1;
            float f3 = (float)entity.damageTaken - f1;
            if(f3 < 0.0F)
            {
                f3 = 0.0F;
            }
            loadTexture("/terrain.png");
            float f4 = 0.75F;
            GL11.glScalef(f4, f4, f4);
            GL11.glScalef(1.0F / f4, 1.0F / f4, 1.0F / f4);
            loadTexture(entity.getTexture());
            GL11.glScalef(-1F, -1F, 1.0F);
            MainModel.render(entity, 0.0F, 0.0F, -0.1F, 0.0F, 0.0F, 0.0625F);
            GL11.glPopMatrix();
        }
    }

    public void doRenderLiving(EntityDinoEgg entityliving, double d, double d1, double d2, 
            float f, float f1)
    {
        renderDinoEgg(entityliving, d, d1, d2, f, f1);
    }

    public void doRender(Entity entity, double d, double d1, double d2, 
            float f, float f1)
    {
        renderDinoEgg((EntityDinoEgg)entity, d, d1, d2, f, f1);
    }
    protected ModelDinoEgg MainModel;
}
